/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GovernementRole.EvaluationRole;

import Business.Enterprise.DistributorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CertificateRequest;
import Business.WorkQueue.GunRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaoh
 */
public class ManageEvaluationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEvaluationJPanel
     */
   
    private JPanel display;
    private UserAccount userAccount;
    private Organization organization;
    private Network network;
   

    public ManageEvaluationJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Network network) {
        initComponents();
        this.display = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.network=network;
       poptable();
        
     
      
    }
      public void poptable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for (Enterprise distributorEnterprise :network.getEnterpriseDirectory().getEnterpriseList()) {
           
           if(distributorEnterprise.getEnterpriseType().getValue().equals("DistributorEnterprise"))
           {
            Object[] row = new Object[5];
            row[0] = distributorEnterprise;
            row[1] = distributorEnterprise.getTotalcustomer();
            row[2] = distributorEnterprise.getRevenue()-distributorEnterprise.getExpense();
            row[3] = distributorEnterprise.getBlocktimes();
            row[4] = distributorEnterprise.getGrade();
            dtm.addRow(row);
        }
          
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        abtn = new javax.swing.JButton();
        bbtn = new javax.swing.JButton();
        cbtn = new javax.swing.JButton();
        dbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5), "Evaluation System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 48))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DistrabutorName", "Total Customer", "Profit", "Block Time(s)", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("<<Back");
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/回滚箭头.jpg"))); // NOI18N

        abtn.setBackground(new java.awt.Color(102, 0, 255));
        abtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        abtn.setText("A");
        abtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnActionPerformed(evt);
            }
        });

        bbtn.setBackground(new java.awt.Color(0, 51, 255));
        bbtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        bbtn.setText("B");
        bbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnActionPerformed(evt);
            }
        });

        cbtn.setBackground(new java.awt.Color(204, 0, 255));
        cbtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        cbtn.setText("C");
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });

        dbtn.setBackground(new java.awt.Color(255, 51, 51));
        dbtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        dbtn.setText("F");
        dbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/GovernementRole/EvaluationRole/宣告.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(abtn)
                .addGap(93, 93, 93)
                .addComponent(bbtn)
                .addGap(93, 93, 93)
                .addComponent(cbtn)
                .addGap(94, 94, 94)
                .addComponent(dbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abtn)
                    .addComponent(bbtn)
                    .addComponent(cbtn)
                    .addComponent(dbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jButton2)
                .addGap(233, 233, 233))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnActionPerformed
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        if(row>=0){
             DistributorEnterprise enterprise1 = (DistributorEnterprise) jTable1.getValueAt(row, 0);
             
             enterprise1.setGrade("A");
            poptable();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a row!");
        
        
        
    }//GEN-LAST:event_abtnActionPerformed

    private void bbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnActionPerformed
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        if(row>=0){
             DistributorEnterprise enterprise1 = (DistributorEnterprise) jTable1.getValueAt(row, 0);
             
             enterprise1.setGrade("B");
            poptable();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a row!");
    }//GEN-LAST:event_bbtnActionPerformed

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        if(row>=0){
             DistributorEnterprise enterprise1 = (DistributorEnterprise) jTable1.getValueAt(row, 0);
             
             enterprise1.setGrade("C");
            poptable();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a row!");
    }//GEN-LAST:event_cbtnActionPerformed

    private void dbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtnActionPerformed
        // TODO add your handling code here:
        int row =jTable1.getSelectedRow();
        if(row>=0){
             DistributorEnterprise enterprise1 = (DistributorEnterprise) jTable1.getValueAt(row, 0);
             
             enterprise1.setGrade("F");
            poptable();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a row!");
    }//GEN-LAST:event_dbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abtn;
    private javax.swing.JButton bbtn;
    private javax.swing.JButton cbtn;
    private javax.swing.JButton dbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
