/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.GovernmentOrganization.CertificateOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CertificateRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reyes
 */
public class ApplyCertificate extends javax.swing.JPanel {

    private JPanel display;
    private UserAccount userAccount;
    private Network network;

    public ApplyCertificate(JPanel display, UserAccount userAccount, Network network) {
        initComponents();
        this.display = display;
        this.userAccount = userAccount;
        this.network = network;
        Sentmailbtn.setText("<html>Sent<br />Mail</html>");
        poptable(true);
        Send.setEnabled(false);
        txt.setEnabled(false);
        if (userAccount.getPerson().isCertificatestatus()) {
            Newbtn.setEnabled(false);
        }

    }

    private void poptable(boolean flag) {
        DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
        dtm.setRowCount(0);
        for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()) {
            if (workRequest instanceof CertificateRequest) {
                if ((flag) && (workRequest.getReceiver() == userAccount)) {
                    Object[] row = new Object[2];
                    CertificateRequest certificateRequest = (CertificateRequest) workRequest;
                    row[0] = certificateRequest.getSender();
                    row[1] = certificateRequest;
                    dtm.addRow(row);
                }
                if ((!flag) && (workRequest.getSender() == userAccount)) {
                    Object[] row = new Object[2];
                    CertificateRequest certificateRequest = (CertificateRequest) workRequest;
                    row[0] = certificateRequest.getReceiver();
                    if (certificateRequest.getReceiver() == null) {
                        row[0] = "Request has not been issued";
                    }
                    row[1] = certificateRequest;
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        Send = new javax.swing.JButton();
        Inboxbtn = new javax.swing.JButton();
        Sentmailbtn = new javax.swing.JButton();
        Newbtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Mail to Apply Certification", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 36)), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 255)), "Mail Certificate Department Officer to Apply Certificate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 2, 18)))); // NOI18N

        jLayeredPane1.setBackground(new java.awt.Color(153, 204, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-Mail Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18), new java.awt.Color(102, 102, 255))); // NOI18N

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane2.setViewportView(txt);

        Send.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Send.setForeground(new java.awt.Color(51, 102, 255));
        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        Inboxbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inboxbtn.setForeground(new java.awt.Color(51, 102, 255));
        Inboxbtn.setText("Inbox");
        Inboxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InboxbtnActionPerformed(evt);
            }
        });

        Sentmailbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sentmailbtn.setForeground(new java.awt.Color(51, 102, 255));
        Sentmailbtn.setText("Sent Mail");
        Sentmailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SentmailbtnActionPerformed(evt);
            }
        });

        Newbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Newbtn.setForeground(new java.awt.Color(51, 102, 255));
        Newbtn.setText("New");
        Newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewbtnActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Send, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Inboxbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Sentmailbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Newbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Newbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sentmailbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inboxbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(Inboxbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sentmailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(Newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Send, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        Back.setBackground(new java.awt.Color(0, 153, 255));
        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setText("<<Back");
        Back.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/回滚箭头.jpg"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SentmailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SentmailbtnActionPerformed
        poptable(false);
        txt.setEnabled(false);
        Send.setEnabled(false);
        txt.setText("");
    }//GEN-LAST:event_SentmailbtnActionPerformed

    private void InboxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InboxbtnActionPerformed
        poptable(true);
        txt.setEnabled(false);
        Send.setEnabled(false);
        txt.setText("");
    }//GEN-LAST:event_InboxbtnActionPerformed

    private void NewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewbtnActionPerformed
        if (userAccount.getPerson().isCertificatelock()) {
            JOptionPane.showMessageDialog(null, "Application has been sent. Please wait for pending!");
            Newbtn.setEnabled(false);
            return;
        }
        txt.setEnabled(true);
        Send.setEnabled(true);
        txt.setText("");
    }//GEN-LAST:event_NewbtnActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        Organization org = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof GovernmentEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof CertificateOrganization) {
                        org = organization;
                    }
                }
            }
        }
        if (org == null) {
            JOptionPane.showMessageDialog(null, "Certificate Department does not exist!");
        }
        CertificateRequest certificateRequest = new CertificateRequest();
        userAccount.getWorkQueue().getWorkRequestList().add(certificateRequest);
        certificateRequest.setStatus("Unprocessed");
        certificateRequest.setSender(userAccount);
        userAccount.getPerson().setCertificatelock(true);
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        certificateRequest.setDate(dateFormat.format(date));
        certificateRequest.setMail(txt.getText());
        org.getWorkQueue().getWorkRequestList().add(certificateRequest);
        JOptionPane.showMessageDialog(null, "Sent succesfully!");
        Send.setEnabled(false);
        poptable(false);

    }//GEN-LAST:event_SendActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int selrow = tbl.getSelectedRow();
        if (selrow < 0) {
            return;
        }
        CertificateRequest certificateRequest = (CertificateRequest) tbl.getValueAt(selrow, 1);
        txt.setText(certificateRequest.getMail());
    }//GEN-LAST:event_tblMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        display.remove(this);
        Component[] componentArray = display.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkArea panel = (CustomerWorkArea) component;
        panel.poplabel();
        CardLayout layout = (CardLayout) display.getLayout();
        layout.previous(display);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Inboxbtn;
    private javax.swing.JButton Newbtn;
    private javax.swing.JButton Send;
    private javax.swing.JButton Sentmailbtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
