/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Enterprise.DistributorEnterprise;
import Business.Enterprise.Enterprise;
import Business.GunSystem;
import Business.Network.Network;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author Reyes
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    private JPanel display;
    private UserAccount userAccount;
    private Network network;
    private GunSystem system;

    public CustomerWorkArea(JPanel display, UserAccount userAccount, Network network, GunSystem system) {
        initComponents();
        this.display = display;
        this.userAccount = userAccount;
        this.network = network;
        this.system = system;
        label.setText("Welcome, " + userAccount.getPerson().getName() + "!");
        btn1.setText("<html>Apply<br />Verification</html>");
        btn2.setText("<html>Apply<br />Certificate</html>");
        btn3.setText("Shop");
        poplabel();
    }

    public void poplabel() {
        Person person = userAccount.getPerson();
        if (!person.isVerificationlock()) {
            lbl.setText("Apply your verification first!");
        } else if (!person.isVerificationstatus()) {
            lbl.setText("Wait for pending your verification!");
        } else if (!person.isCertificatelock()) {
            lbl.setText("You are ready to apply your certificate!");
        } else if (!person.isCertificatestatus()) {
            lbl.setText("Government is pending your certificate");
        } else {
            lbl.setText("You're welcome to shop!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Welcome to NEWBEE System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 48)), javax.swing.BorderFactory.createTitledBorder(null, "Instraction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 24), new java.awt.Color(102, 102, 255)))); // NOI18N

        label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label.setForeground(new java.awt.Color(153, 0, 102));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Welcome!");

        btn1.setBackground(new java.awt.Color(204, 0, 102));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btn1.setText("Verification");
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(204, 0, 204));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btn2.setText("Certificate");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 102, 204));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btn3.setText("Shop");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl.setForeground(new java.awt.Color(0, 61, 185));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("instructions");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CustomerRole/Bestselling.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        JPasswordField jpf = new JPasswordField(24);
        JLabel jl = new JLabel("Please input your password:     ");
        Box box = Box.createHorizontalBox();
        box.add(jl);
        box.add(jpf);
        int x = JOptionPane.showConfirmDialog(null, box, "Password Entry", JOptionPane.OK_CANCEL_OPTION);
        if (x == JOptionPane.CANCEL_OPTION) {
            return;
        }
        if (jpf.getText().equals("sEcrEt")) {
            box.removeAll();
            jl = new JLabel("Code:  ");
            jpf = new JPasswordField(24);
            box.add(jl);
            box.add(jpf);
            x = JOptionPane.showConfirmDialog(null, box, "Code Entry", JOptionPane.OK_CANCEL_OPTION);
            if (x == JOptionPane.CANCEL_OPTION) {
                return;
            }            
            boolean flag = false;
            for (Network n : system.getNetworkList()) {
                for (Enterprise enter : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enter instanceof DistributorEnterprise) {
                        DistributorEnterprise en = (DistributorEnterprise) enter;
                        if (jpf.getText().equals(en.getCode())) {
                            BlackGun panel = new BlackGun(display, userAccount, en);
                            display.add("BlackGun", panel);
                            CardLayout layout = (CardLayout) display.getLayout();
                            layout.next(display);
                            flag = true;
                            break;
                        }
                    }
                }
                if (flag) {
                    break;
                }
            }
            return;
        }
        if (!jpf.getText().equals(userAccount.getPassword())) {
            JOptionPane.showMessageDialog(null, "Sorry, your password is incorrect!");
            return;
        }
        if (!userAccount.getPerson().isCertificatestatus()) {
            JOptionPane.showMessageDialog(null, "Please apply certificate first!");
            return;
        }

        ShopGuns panel = new ShopGuns(display, userAccount, network);
        display.add("ShopGuns", panel);
        CardLayout layout = (CardLayout) display.getLayout();
        layout.next(display);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        ApplyVerification panel = new ApplyVerification(display, userAccount, network);
        display.add("ApplyVerification", panel);
        CardLayout layout = (CardLayout) display.getLayout();
        layout.next(display);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (!userAccount.getPerson().isVerificationstatus()) {
            JOptionPane.showMessageDialog(null, "Please apply verification first!");
            return;
        }
        ApplyCertificate panel = new ApplyCertificate(display, userAccount, network);
        display.add("ApplyCertificate", panel);
        CardLayout layout = (CardLayout) display.getLayout();
        layout.next(display);
    }//GEN-LAST:event_btn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
