/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManufactureRole;

import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.ManufactorEnterprise;
import Business.Enterprise.ManufactorEnterprise;
import Business.Gun.Bullet;
import Business.Gun.BulletInventoryitem;
import Business.Gun.Gun;
import Business.Gun.GunBulletSystem;
import Business.Gun.GunInventoryitem;
import Business.Material.Material;
import Business.Material.MaterialInventoryitem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GunRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.WorkQueue.BulletRequst;

/**
 *
 * @author yuzix
 */
public class Manufactorwork extends javax.swing.JPanel {

    /**
     * Creates new form Manufactorwork
     */
    JPanel userProcessContainer;
    ManufactorEnterprise manufactorEnterprise;
    UserAccount userAccount;
    GunBulletSystem gunBulletSystem;
    int materialtotalprice;
    int changeprice=0;

    Manufactorwork(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.manufactorEnterprise = (ManufactorEnterprise) enterprise;

        gunBulletSystem = GunBulletSystem.getInstance();
        materialtotalprice=manufactorEnterprise.getExpense();
         expenseTF.setText(Integer.toString(materialtotalprice));
        
        
     
        
        populatematerialbox();
        populatematerialtable();
        populatebullettable();
        populateproductmaterialtable();
        populateguntable();
        popgunbox();
        popbulletbox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        materialTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        quantitySpinner1 = new javax.swing.JSpinner();
        materialbackBtn = new javax.swing.JButton();
        materialComboBox = new javax.swing.JComboBox();
        priceTF = new javax.swing.JTextField();
        expenseTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buybTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        productbulletTable = new javax.swing.JTable();
        cbulletBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productmaterialTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        productgunTable = new javax.swing.JTable();
        creategunBtn = new javax.swing.JButton();
        gunComboBox = new javax.swing.JComboBox();
        bulletComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        quantitySpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        quantitySpinner3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        wantTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        wantbulletTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 5, true), "Material Import", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 48))); // NOI18N

        materialTable.setBackground(new java.awt.Color(204, 255, 255));
        materialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Material", "Quantity", "Average Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(materialTable);

        jLabel2.setText("Quantity:");

        quantitySpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantitySpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantitySpinner1KeyTyped(evt);
            }
        });

        materialbackBtn.setBackground(new java.awt.Color(102, 153, 255));
        materialbackBtn.setText("<<Back");
        materialbackBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/回滚箭头.jpg"))); // NOI18N
        materialbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialbackBtnActionPerformed(evt);
            }
        });

        materialComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        materialComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialComboBoxActionPerformed(evt);
            }
        });

        priceTF.setEnabled(false);

        expenseTF.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        expenseTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(153, 102, 255)));
        expenseTF.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Expense:");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(153, 102, 255)));

        buybTN.setBackground(new java.awt.Color(153, 153, 255));
        buybTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        buybTN.setText("Buy Material");
        buybTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buybTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expenseTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(quantitySpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buybTN)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(materialbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(quantitySpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(expenseTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buybTN))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)))
                .addComponent(materialbackBtn)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Material", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 5, true), "Create Guns & Bullets", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 48))); // NOI18N

        backBtn.setBackground(new java.awt.Color(51, 204, 255));
        backBtn.setText("<<Back");
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        backBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/回滚箭头.jpg"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        productbulletTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bullet", "Quantity", "Average Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(productbulletTable);

        cbulletBtn.setBackground(new java.awt.Color(255, 255, 255));
        cbulletBtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        cbulletBtn.setForeground(new java.awt.Color(51, 51, 255));
        cbulletBtn.setText("Create Bullet");
        cbulletBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray));
        cbulletBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbulletBtnActionPerformed(evt);
            }
        });

        productmaterialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productmaterialTable);

        productgunTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Gun", "Quantity", "Average Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productgunTable);

        creategunBtn.setBackground(new java.awt.Color(255, 255, 255));
        creategunBtn.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        creategunBtn.setForeground(new java.awt.Color(51, 51, 255));
        creategunBtn.setText("Create Gun ");
        creategunBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray));
        creategunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creategunBtnActionPerformed(evt);
            }
        });

        gunComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gunComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunComboBoxActionPerformed(evt);
            }
        });

        bulletComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bulletComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulletComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantity:");

        quantitySpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantitySpinner2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantitySpinner2KeyTyped(evt);
            }
        });

        jLabel4.setText("Quantity:");

        quantitySpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        quantitySpinner3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantitySpinner3KeyTyped(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12)); // NOI18N
        jLabel5.setText("Material inSock:");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)))));

        jSeparator2.setForeground(new java.awt.Color(102, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0))), javax.swing.BorderFactory.createTitledBorder(null, "Create Bullets:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 3, 18)))); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(102, 255, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createTitledBorder(null, "Create Guns:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 3, 18)))); // NOI18N

        jLabel6.setText("Want profit:");

        wantTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wantTFKeyTyped(evt);
            }
        });

        jLabel8.setText("Want profit:");

        wantbulletTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wantbulletTFKeyTyped(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/SR.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/AR.jpg"))); // NOI18N
        jLabel9.setText("jLabel7");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/Pistol.jpg"))); // NOI18N
        jLabel10.setText("jLabel7");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/ShootGun.jpg"))); // NOI18N
        jLabel11.setText("jLabel7");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ManufactureRole/SMG.jpg"))); // NOI18N
        jLabel12.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantitySpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(gunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(wantTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bulletComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(wantbulletTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(quantitySpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18))))
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(creategunBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(429, 429, 429)
                        .addComponent(cbulletBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulletComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitySpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(quantitySpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(wantTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(wantbulletTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creategunBtn)
                    .addComponent(cbulletBtn))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Product", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quantitySpinner3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitySpinner3KeyTyped
        txt3KeyTyped(evt);
    }//GEN-LAST:event_quantitySpinner3KeyTyped

    private void quantitySpinner2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitySpinner2KeyTyped
        txt3KeyTyped(evt);
    }//GEN-LAST:event_quantitySpinner2KeyTyped

    private void bulletComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulletComboBoxActionPerformed
        // TODO add your handling code here:
        quantitySpinner3.setValue(0);
        wantbulletTF.setText(Integer.toString(0));
    }//GEN-LAST:event_bulletComboBoxActionPerformed

    private void gunComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunComboBoxActionPerformed
        // TODO add your handling code here:
        quantitySpinner2.setValue(0);
        wantTF.setText(Integer.toString(0));
    }//GEN-LAST:event_gunComboBoxActionPerformed

    private void creategunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creategunBtnActionPerformed
        int quantity = (Integer) quantitySpinner2.getValue();

        Gun gun = (Gun) gunComboBox.getSelectedItem();
        int p=manufactorEnterprise.findgunnumber(gun, quantity);

        if(p>=0)
        {
            GunInventoryitem gunInventoryitem = manufactorEnterprise.findguninventory(gun);

            if (gunInventoryitem != null) {

                int oldquantity=gunInventoryitem.getGuninventory();
                int oldprice=gunInventoryitem.getPrice();
                int price=(quantity*p+oldprice*oldquantity)/(quantity+oldquantity);
                gunInventoryitem.setPrice(price+(Integer.valueOf(wantTF.getText())));
                
                gunInventoryitem.setSaleprice(price+(Integer.valueOf(wantTF.getText())));
                

                gunInventoryitem.setnum(quantity);

            } else {
                manufactorEnterprise.createguninventoryitem(gun, quantity,p);

            }
            populateguntable();
            populatematerialtable();
            populateproductmaterialtable();
        }
        else
        {JOptionPane.showMessageDialog(null,"Inventory Error");}
    }//GEN-LAST:event_creategunBtnActionPerformed

    private void cbulletBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbulletBtnActionPerformed
        int quantity = (Integer) quantitySpinner3.getValue();
        int p= manufactorEnterprise.createbullet(quantity);
        if(p>0)
        {
            Bullet bullet = (Bullet) bulletComboBox.getSelectedItem();
            BulletInventoryitem bulletInventoryitem = manufactorEnterprise.findbulletinventory(bullet);
            if (bulletInventoryitem != null) {
                int oldquantity=bulletInventoryitem.getBulletinventory();
                int oldprice=bulletInventoryitem.getPrice();
                int price=(quantity*p+oldprice*oldquantity)/(quantity+oldquantity);
                bulletInventoryitem.setPrice(price+(Integer.valueOf(wantbulletTF.getText())));
                
                bulletInventoryitem.setSaleprice(price +(Integer.valueOf(wantbulletTF.getText())));
                 System.out.println(bulletInventoryitem.getSaleprice());
                bulletInventoryitem.setnum(quantity);

            } else {
                manufactorEnterprise.createbulletinventoryitem(bullet, quantity,p);

            }
            populatebullettable();
            populatematerialtable();
            populateproductmaterialtable();
        }
        else
        {JOptionPane.showMessageDialog(null,"Inventory Error");}
    }//GEN-LAST:event_cbulletBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void materialComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialComboBoxActionPerformed
        int num =(int)(Math.random() * 10+1);

        priceTF.setText(Integer.toString(num));
        quantitySpinner1.setValue(0);
    }//GEN-LAST:event_materialComboBoxActionPerformed

    private void materialbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialbackBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_materialbackBtnActionPerformed

    private void quantitySpinner1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitySpinner1KeyTyped
        txt3KeyTyped(evt);
    }//GEN-LAST:event_quantitySpinner1KeyTyped

    private void wantTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wantTFKeyTyped
        // TODO add your handling code here:
         txt3KeyTyped(evt);
    }//GEN-LAST:event_wantTFKeyTyped

    private void wantbulletTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wantbulletTFKeyTyped
        // TODO add your handling code here:
        txt3KeyTyped(evt);
    }//GEN-LAST:event_wantbulletTFKeyTyped

    private void buybTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buybTNActionPerformed
        // TODO add your handling code here:
         int quantity = (Integer) quantitySpinner1.getValue();

        Material material = (Material) materialComboBox.getSelectedItem();
        int p=Integer.valueOf(priceTF.getText());
        materialtotalprice=materialtotalprice+p*quantity;
        MaterialInventoryitem materialInventoryitem = manufactorEnterprise.findInventory(material);

        if ((materialInventoryitem != null)) {
            int oldquantity=materialInventoryitem.getQunatity();
            int oldprice=materialInventoryitem.getPrice();
            int price=(quantity*p+oldprice*oldquantity)/(quantity+oldquantity);
            materialInventoryitem.setPrice(price);
            materialInventoryitem.setnum(quantity);

        } else {
            manufactorEnterprise.creatematerialinventory(material, quantity,p);

        }

        populatematerialtable();
        populateproductmaterialtable();
        expenseTF.setText(Integer.toString(materialtotalprice));
        manufactorEnterprise.setExpense(materialtotalprice);
    }//GEN-LAST:event_buybTNActionPerformed
      public void populatematerialtable() {
        DefaultTableModel model = (DefaultTableModel) materialTable.getModel();
        model.setRowCount(0);

        for (MaterialInventoryitem material : manufactorEnterprise.getMaterialInventory()) {
            Object[] row = new Object[3];
            row[0] = material.getMaterial();
            row[1] = material.getQunatity();
            row[2] = material.getPrice();
            model.addRow(row);
        }
    }

    public void populateproductmaterialtable() {
        DefaultTableModel model = (DefaultTableModel) productmaterialTable.getModel();
        model.setRowCount(0);

        for (MaterialInventoryitem materialInventoryitem : manufactorEnterprise.getMaterialInventory()) {
            Object[] row = new Object[2];
            row[0] = materialInventoryitem.getMaterial();
            row[1] = materialInventoryitem.getQunatity();
            model.addRow(row);
        }
    }

    public void popgunbox() {
        gunComboBox.removeAllItems();
        for (Gun gun : gunBulletSystem.getGunDirectory().getGunList()) {
            gunComboBox.addItem(gun);
        }
    }

    public void popbulletbox() {
        bulletComboBox.removeAllItems();
        for (Bullet b : gunBulletSystem.getBulletDirectory().getBulletList()) {
            bulletComboBox.addItem(b);
        }
    }

    public void populateguntable() {
        DefaultTableModel model = (DefaultTableModel) productgunTable.getModel();
        model.setRowCount(0);

        for (GunInventoryitem gunInventory : manufactorEnterprise.getGunInventory()) {
            Object[] row = new Object[3];
            row[0] = gunInventory.getGun();
            row[1] = gunInventory.getGuninventory();
            row[2] = gunInventory.getPrice();
            model.addRow(row);
        }
    }

    public void populatebullettable() {
        DefaultTableModel model = (DefaultTableModel) productbulletTable.getModel();
        model.setRowCount(0);

        for (BulletInventoryitem bulletInventory : manufactorEnterprise.getBulletInventory()) {
            Object[] row = new Object[3];
            row[0] = bulletInventory.getBullet();
            row[1] = bulletInventory.getBulletinventory();
            row[2] = bulletInventory.getPrice();
            model.addRow(row);
        }
    }

    

    

    public void populatematerialbox() {
        materialComboBox.removeAllItems();
        for (Material material : gunBulletSystem.getMaterialDirectory().getMaterialList()) {
            materialComboBox.addItem(material);
        }
    }
    private void txt3KeyTyped(java.awt.event.KeyEvent evt) {                              
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox bulletComboBox;
    private javax.swing.JButton buybTN;
    private javax.swing.JButton cbulletBtn;
    private javax.swing.JButton creategunBtn;
    private javax.swing.JTextField expenseTF;
    private javax.swing.JComboBox gunComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox materialComboBox;
    private javax.swing.JTable materialTable;
    private javax.swing.JButton materialbackBtn;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTable productbulletTable;
    private javax.swing.JTable productgunTable;
    private javax.swing.JTable productmaterialTable;
    private javax.swing.JSpinner quantitySpinner1;
    private javax.swing.JSpinner quantitySpinner2;
    private javax.swing.JSpinner quantitySpinner3;
    private javax.swing.JTextField wantTF;
    private javax.swing.JTextField wantbulletTF;
    // End of variables declaration//GEN-END:variables
}
